---
- name: Setup Docker, Git, Jenkins, and Kubernetes
  hosts: localhost
  become: yes
  tasks:
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Set JAVA_HOME environment variable
      lineinfile:
        path: /etc/environment
        line: "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64"
        create: yes
        state: present

    - name: Download Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: Add Jenkins APT repository
      ansible.builtin.apt_repository:
        repo: 'deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/'
        filename: jenkins
        state: present

    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Enable Jenkins service
      systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started

    - name: Ensure Jenkins is listening on port 8080
      wait_for:
        port: 8080
        delay: 10
        state: started

    - name: Allow current user to use sudo without a password
      copy:
        dest: "/etc/sudoers.d/{{ ansible_env.USER }}"
        content: "{{ ansible_env.USER }} ALL=(ALL) NOPASSWD:ALL"
        mode: '0440'
        validate: 'visudo -cf %s'


    - name: Add Kubernetes APT repository
      apt_repository:
        repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
        filename: kubernetes
        state: present

    - name: Add Kubernetes GPG key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Install Kubernetes components
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes
